//! Cell-based text helpers: East Asian Wide/Fullwidth and Ambiguous
//! characters count as 2 cells, matching how the bundled font renders them.

use egui::{Color32, TextStyle, Ui};
use unicode_width::UnicodeWidthChar;

/// Cells one char occupies: East Asian Wide/Fullwidth and Ambiguous = 2,
/// control and zero-width chars = 0, everything else = 1, except where the
/// bundled font's advance disagrees (see [`BUNDLED_FONT_OVERRIDES`]).
pub fn char_cells(c: char) -> usize {
    let cp = c as u32;
    BUNDLED_FONT_OVERRIDES
        .iter()
        .find(|(lo, hi, _)| (*lo..=*hi).contains(&cp))
        .map_or_else(|| c.width_cjk().unwrap_or(0), |&(_, _, w)| w)
}

/// Code point ranges where the bundled font's advance width differs from
/// `width_cjk`: `(first, last, cells)`. The font follows JIS X 0208, which
/// draws Greek, Cyrillic, U+2212 and a few Latin-1 signs full-width, and its
/// Private Use Area glyphs half-width. Generated by comparing the font's
/// `hmtx` advances against `unicode-width` 0.2.
const BUNDLED_FONT_OVERRIDES: &[(u32, u32, usize)] = &[
    (0x00A2, 0x00A3, 2), // ¢ £
    (0x00A8, 0x00A8, 2), // ¨
    (0x00AC, 0x00AC, 2), // ¬
    (0x00B4, 0x00B4, 2), // ´
    (0x0391, 0x03A9, 2), // Greek capitals
    (0x03B1, 0x03C9, 2), // Greek small letters
    (0x0401, 0x0401, 2), // Ё
    (0x0410, 0x044F, 2), // Cyrillic А..я
    (0x0451, 0x0451, 2), // ё
    (0x2000, 0x200A, 2), // en quad .. hair space
    (0x203E, 0x203E, 1), // ‾
    (0x212B, 0x212B, 2), // Å (angstrom sign)
    (0x2212, 0x2212, 2), // − (the font's full-width minus)
    (0xE000, 0xE0FF, 1), // Private Use Area glyphs
];

/// Sum of `char_cells` over `s`.
pub fn cells(s: &str) -> usize {
    // A per-char sum (not `UnicodeWidthStr::width_cjk`) so it matches
    // per-glyph rendering and `cells(truncate_cells(s, n)) <= n` always holds.
    s.chars().map(char_cells).sum()
}

/// Longest prefix of `s` that fits in `max` cells; never splits a wide char.
pub fn truncate_cells(s: &str, max: usize) -> &str {
    let mut used = 0;
    for (i, c) in s.char_indices() {
        let w = char_cells(c);
        if used + w > max {
            return &s[..i];
        }
        used += w;
    }
    s
}

/// `s` if it fits in `max` cells, else a prefix plus ASCII "..." totalling at most `max` cells.
pub fn truncate_tail(s: &str, max: usize) -> String {
    if cells(s) <= max {
        return s.to_owned();
    }
    if max <= 3 {
        return ".".repeat(max);
    }
    format!("{}...", truncate_cells(s, max - 3))
}

/// Width in points of one half-width cell in the `Body` font of `ui`.
pub fn cell_width(ui: &Ui) -> f32 {
    // Measuring an actual glyph (rather than `font_size / 2`) keeps this
    // correct for substitute fonts when `bundled-font` is disabled.
    let galley = ui.painter().layout_no_wrap(
        "0".to_owned(),
        TextStyle::Body.resolve(ui.style()),
        Color32::WHITE,
    );
    galley.size().x
}

#[cfg(test)]
mod tests {
    use egui::RawInput;

    use crate::Palette;
    use crate::style::apply_with;

    use super::*;

    #[test]
    fn cells_counts_ascii_wide_and_control() {
        assert_eq!(cells("abc"), 3);
        assert_eq!(cells("日本"), 4);
        assert_eq!(cells("○×α"), 6);
        assert_eq!(cells("\n"), 0);
    }

    #[test]
    fn bundled_font_overrides_apply() {
        // `width_cjk` says 1 for these; the bundled font draws them full-width.
        assert_eq!(cells("Ωя−£"), 8);
        // And the reverse: `width_cjk` says 2, the font draws half-width.
        assert_eq!(char_cells('\u{203E}'), 1);
    }

    #[test]
    fn truncate_cells_never_splits_a_wide_char() {
        assert_eq!(truncate_cells("日本語", 3), "日");
        assert_eq!(truncate_cells("abc", 10), "abc");
        assert_eq!(truncate_cells("", 0), "");
    }

    #[test]
    fn truncate_tail_appends_ascii_ellipsis() {
        assert_eq!(truncate_tail("abcdefgh", 6), "abc...");
        assert_eq!(truncate_tail("日本語テキスト", 7), "日本...");
        assert_eq!(truncate_tail("ab", 2), "ab");
        assert_eq!(truncate_tail("abcdef", 2), "..");
    }

    #[test]
    fn truncate_tail_never_exceeds_max_cells() {
        let samples = ["", "a", "abcdefghij", "日本語テキスト", "○×°123", "\n\t"];
        for s in samples {
            for max in 0..12 {
                assert!(
                    cells(&truncate_tail(s, max)) <= max,
                    "truncate_tail({s:?}, {max}) exceeded {max} cells"
                );
            }
        }
    }

    #[test]
    fn cell_width_is_positive() {
        let ctx = egui::Context::default();
        apply_with(&ctx, &Palette::default());

        let mut width = 0.0;
        let mut output = ctx.run_ui(RawInput::default(), |ui| {
            width = cell_width(ui);
        });
        output.textures_delta.clear();

        assert!(width > 0.0);
    }
}
